#!/usr/bin/env python3
"""The resources of the Uposatha widgets (v2: seven separate widgets, each ONE design that WidgetViews scales to the cell).
Writes res/layout/w2_*.xml, res/drawable/w2_*.xml and the colours. Run from uposatha/: python3 widget/tools/gen_android_res.py

The layouts hold only the STRUCTURE (which views, in what order); every size (text, padding, the pictures) is set by WidgetViews,
multiplied by the scale of the widget. Colours: a drawable has three files: plain (colour resources with a night variant, the launcher
follows the system theme by itself), _lt and _dk (fixed, for a widget whose own setting says "always light / always dark")."""
import os

RES = 'android/app/src/main/res'
NS = 'xmlns:android="http://schemas.android.com/apk/res/android"'
HEAD = '<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by widget/tools/gen_android_res.py: edit the script, not this file. -->\n'

# name: (light, dark)
PALETTE = {
    'surface': ('#EEF4F2', '#1A211F'), 'tile': ('#FFFFFF', '#252D2B'), 'text': ('#1B1D19', '#E2E2E2'), 'text2': ('#5C6058', '#B0B0B0'),
    'muted': ('#6E716A', '#8E8E8E'), 'accent': ('#149C7C', '#149C7C'), 'accent_ink': ('#0F7C63', '#1FB394'), 'border': ('#D9E3E0', '#2C3533'),
    'vik': ('#9B1C31', '#E0607A'), 'band': ('#CFE9E2', '#17312C'), 'gold': ('#C4972F', '#C9A13A'), 'goldbg': ('#F5EAD0', '#3A3220'), 'goldov': ('#66C4972F', '#73C9A13A'),
    'plate': ('#D1D7DD', '#393F44'), 'border_strong': ('#C3CFCB', '#414B49'), 'part_day': ('#BDE3DA', '#1D3A34'), 'part_night': ('#C1C9D0', '#444C54'), 'on_accent': ('#FFFFFF', '#FFFFFF'),
}


def write(path, body):
    p = os.path.join(RES, path)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w', encoding='utf-8') as f:
        f.write(HEAD + body.strip() + '\n')


def colours():
    for night, idx in (('values', 0), ('values-night', 1)):
        rows = ''.join('    <color name="w_%s">%s</color>\n' % (k, v[idx]) for k, v in PALETTE.items())
        write(night + '/widget_colors.xml', '<resources>\n' + rows +
              '    <!-- the moon pair: the light picture shows on a light card, the one with the halo on a dark card (alpha, because a layout cannot switch visibility by theme) -->\n'
              '    <item name="w_alpha_light" format="float" type="dimen">%d</item>\n    <item name="w_alpha_dark" format="float" type="dimen">%d</item>\n</resources>' % (1 - idx, idx))
    write('values/widget_dimens.xml', '<resources>\n    <dimen name="w2_radius">24dp</dimen>\n</resources>')
    write('values-v31/widget_dimens.xml', '<resources>\n    <dimen name="w2_radius">@android:dimen/system_app_widget_background_radius</dimen>\n</resources>')


def shape(fill, radius, stroke=None):
    s = '<shape %s android:shape="rectangle"><solid android:color="%s" /><corners android:radius="%s" />' % (NS, fill, radius)
    if stroke: s += '<stroke android:width="1.5dp" android:color="%s" />' % stroke
    return s + '</shape>'


def drawables():
    # name: (fill key, radius, stroke key)
    specs = {'w2_tile': ('tile', '9dp', None), 'w2_tile_day': ('band', '9dp', None), 'w2_tile_today': ('goldbg', '9dp', 'gold'),
             'w2_ring': ('goldov', '9dp', 'gold'),   # today: a translucent gold plaque with its frame, drawn OVER the capsule of an Uposatha (a frame alone can be lost on it)
             'w2_card': ('tile', '14dp', None), 'w2_badge': ('band', '9dp', None), 'w2_plate': ('plate', '8dp', None)}
    for name, (fill, r, stroke) in specs.items():
        write('drawable/%s.xml' % name, shape('@color/w_' + fill if fill else '#00000000', r, stroke and '@color/w_' + stroke))
        for suf, idx in (('_lt', 0), ('_dk', 1)):
            write('drawable/%s%s.xml' % (name, suf), shape(PALETTE[fill][idx] if fill else '#00000000', r, stroke and PALETTE[stroke][idx]))
    write('drawable/w2_bg.xml', shape('@color/w_surface', '@dimen/w2_radius'))   # tinted by WidgetViews when the theme is forced; its alpha is the widget's opacity
    write('drawable/w2_seg.xml', shape('#FFFFFFFF', '3dp').replace('<solid', '<size android:width="22dp" android:height="5dp" /><solid'))   # a dot of the slides' switch, tinted by WidgetViews
    write('drawable/w2_band.xml', '<shape %s android:shape="rectangle"><solid android:color="%s" /></shape>' % (NS, PALETTE['accent'][0]))   # joins the dates of one Uposatha
    write('drawable/w2_dot.xml', '<shape %s android:shape="oval"><solid android:color="%s" /></shape>' % (NS, PALETTE['accent'][0]))
    for n, d in (('w2_chev_l', 'M15,5 L8,12 L15,19'), ('w2_chev_r', 'M9,5 L16,12 L9,19')):
        write('drawable/%s.xml' % n, '<vector %s android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">'
              '<path android:pathData="%s" android:strokeColor="#FFFFFFFF" android:strokeWidth="2" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" /></vector>' % (NS, d))


# ---------------------------------------------------------------- layout pieces
def tv(i, style, extra=''):
    return '<TextView android:id="@+id/%s" style="@style/%s" android:layout_width="wrap_content" android:layout_height="wrap_content" %s/>' % (i, style, extra)


def lin(i, orient, children, extra='android:layout_width="wrap_content" android:layout_height="wrap_content"'):
    idattr = 'android:id="@+id/%s" ' % i if i else ''
    return '<LinearLayout %sandroid:orientation="%s" android:baselineAligned="false" %s>\n%s\n</LinearLayout>' % (idattr, orient, extra, '\n'.join(children))


FILL = '<FrameLayout android:layout_width="0dp" android:layout_height="1dp" android:layout_weight="1" />'
MOON = ('<FrameLayout android:id="@+id/moon" android:layout_width="wrap_content" android:layout_height="wrap_content">'
        '<ImageView android:id="@+id/moon_l" android:layout_width="wrap_content" android:layout_height="wrap_content" android:alpha="@dimen/w_alpha_light" android:importantForAccessibility="no" />'
        '<ImageView android:id="@+id/moon_d" android:layout_width="wrap_content" android:layout_height="wrap_content" android:alpha="@dimen/w_alpha_dark" android:importantForAccessibility="no" />'
        '<ImageView android:id="@+id/moon_x" android:layout_width="wrap_content" android:layout_height="wrap_content" android:visibility="gone" android:importantForAccessibility="no" />'   # a forced theme: this one, whatever the system says
        '</FrameLayout>')
PCROW = lin('pc_row', 'horizontal', [tv('pc', 'W_S'), tv('pc_ar', 'W_TM')], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="bottom"')
COUNTER = lin('cnt', 'horizontal', [tv('c_dn', 'W_T', 'android:fontFeatureSettings="tnum" android:letterSpacing="-0.015"'), tv('c_du', 'W_S'),
                                    tv('c_hn', 'W_T', 'android:fontFeatureSettings="tnum" android:letterSpacing="-0.015"'), tv('c_hu', 'W_S')],
              'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="bottom" android:baselineAligned="true"').replace('android:baselineAligned="false" ', '')
KALA = lin('kala', 'horizontal', [tv('k_word', 'W_B'), tv('k_mid', 'W_T'), tv('k_time', 'W_B', 'android:fontFeatureSettings="tnum"')])
WHEN_COL = lambda grav: lin('when', 'vertical', [tv('dt', 'W_S'), tv('tm', 'W_TM')], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="%s"' % grav)
BAR = ('<FrameLayout android:id="@+id/bar" android:layout_width="match_parent" android:layout_height="wrap_content">'
       '<ImageView android:id="@+id/bar_l" android:layout_width="match_parent" android:layout_height="wrap_content" android:scaleType="fitXY" android:adjustViewBounds="true" android:alpha="@dimen/w_alpha_light" android:importantForAccessibility="no" />'
       '<ImageView android:id="@+id/bar_d" android:layout_width="match_parent" android:layout_height="wrap_content" android:scaleType="fitXY" android:adjustViewBounds="true" android:alpha="@dimen/w_alpha_dark" android:importantForAccessibility="no" />'
       '<ImageView android:id="@+id/bar_x" android:layout_width="match_parent" android:layout_height="wrap_content" android:scaleType="fitXY" android:adjustViewBounds="true" android:visibility="gone" android:importantForAccessibility="no" />'
       '</FrameLayout>')
MATCH = 'android:layout_width="match_parent" android:layout_height="match_parent"'
ROWW = 'android:layout_width="match_parent" android:layout_height="wrap_content"'


def root(content):
    return ('<FrameLayout %s android:id="@android:id/background" %s>\n'
            '<ImageView android:id="@+id/w_bg" %s android:scaleType="fitXY" android:src="@drawable/w2_bg" android:importantForAccessibility="no" />\n%s\n'
            # the switch of the slides is put in here and taken out again on every draw (WidgetViews.frame): a launcher draws onto the views it has
            '<FrameLayout android:id="@+id/sw_host" %s />\n</FrameLayout>' % (NS, MATCH, MATCH, content, MATCH))


def layouts():
    # Moon 1x1
    write('layout/w2_moon.xml', root(lin('w_c', 'vertical', [MOON, PCROW], MATCH + ' android:gravity="center"')))
    # Moon + Uposatha 2x1
    write('layout/w2_moonupo.xml', root(lin('w_c', 'horizontal', [
        lin('col_l', 'vertical', [MOON, PCROW], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="center_horizontal"'),
        lin('col_r', 'vertical', [tv('nday', 'W_BA'), COUNTER, tv('state', 'W_TM')])], MATCH + ' android:gravity="center"')))
    # Uposatha 2x2, a wide cell: the agreed 1A / 1B
    write('layout/w2_upo_wide.xml', root(lin('w_c', 'vertical', [
        lin('r1', 'horizontal', [MOON, tv('st', 'W_BA')], ROWW + ' android:gravity="center_vertical"'),
        lin('r2', 'horizontal', [COUNTER, FILL, WHEN_COL('end')], ROWW + ' android:gravity="bottom"'),
        tv('ml', 'W_TM'), KALA], MATCH + ' android:gravity="center_vertical"')))
    # Uposatha 2x2, a narrow cell: the same lines, stacked (when_a: date and time in one line; when_b: in two)
    write('layout/w2_upo_stack.xml', root(lin('w_c', 'vertical', [
        lin('r1', 'horizontal', [lin('col_l', 'vertical', [MOON, PCROW], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="center_horizontal"'),
                                 lin('col_st', 'vertical', [tv('st1', 'W_BA'), tv('st2', 'W_BA')])], ROWW + ' android:gravity="center_vertical"'),
        COUNTER,
        lin('when_a', 'horizontal', [tv('dt_a', 'W_S'), tv('tm_a', 'W_TM')]),
        lin('when_b', 'vertical', [tv('dt_b', 'W_S'), tv('tm_b', 'W_TM')]),
        tv('ml', 'W_TM'), KALA], MATCH + ' android:gravity="center_vertical"')))
    # Uposatha 4x1
    write('layout/w2_strip.xml', root(lin('w_c', 'horizontal', [MOON, lin('col_r', 'vertical', [
        lin('l1', 'horizontal', [tv('st', 'W_BA'), FILL, PCROW], ROWW + ' android:gravity="center_vertical"'),
        lin('r2', 'horizontal', [COUNTER, WHEN_COL('start')], ROWW + ' android:gravity="bottom"'),
        KALA], 'android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1"')], MATCH + ' android:gravity="center_vertical"')))
    # Uposatha 4x1 in a low wide cell (a 75 dp row): the moon, the counter, then the state with the percent, the date with the time, kala
    write('layout/w2_strip_w.xml', root(lin('w_c', 'horizontal', [MOON, COUNTER,
        lin('col_r', 'vertical', [
            lin('l1', 'horizontal', [tv('st', 'W_BA'), FILL, PCROW], ROWW + ' android:gravity="center_vertical"'),
            lin('l2', 'horizontal', [tv('dt', 'W_S'), tv('tm', 'W_TM')], ROWW),
            KALA], 'android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1"')],
        MATCH + ' android:gravity="center_vertical"')))
    # Uposatha 4x2
    write('layout/w2_upo_m.xml', root(lin('w_c', 'horizontal', [MOON, lin('col_r', 'vertical', [
        tv('st', 'W_BA'),
        lin('r2', 'horizontal', [COUNTER, WHEN_COL('start')], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="bottom"'),
        tv('ml', 'W_TM'), tv('dl', 'W_T2'), KALA])], MATCH + ' android:gravity="center"')))
    # Uposatha in a tall cell (a slide of the big widget): the same block, then the next Uposathas and the sun of today
    sun_row = lin('sun', 'horizontal', sum([[tv('s%dl' % i, 'W_T2'), tv('s%dt' % i, 'W_S', 'android:fontFeatureSettings="tnum"')] + ([FILL] if i < 2 else []) for i in range(3)], []), ROWW)
    write('layout/w2_upo_l.xml', root(lin('w_c', 'vertical', [
        lin('hero', 'horizontal', [MOON, lin('col_r', 'vertical', [
            tv('st', 'W_BA'),
            lin('r2', 'horizontal', [COUNTER, WHEN_COL('start')], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="bottom"'),
            tv('ml', 'W_TM'), tv('dl', 'W_T2'), KALA])], ROWW + ' android:gravity="center_vertical"'),
        lin('nx', 'vertical', [tv('nlab', 'W_TM', 'android:textAllCaps="true" android:letterSpacing="0.09"'), lin('nlist', 'vertical', [], ROWW)], 'android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"'),
        sun_row], MATCH)))
    # Day & night, a narrow cell
    ticks = lambda n: lin('tks', 'horizontal', sum([[tv('tk%d' % i, 'W_TM', 'android:fontFeatureSettings="tnum"')] + ([FILL] if i < n - 1 else []) for i in range(n)], []), ROWW)
    write('layout/w2_day_s.xml', root(lin('w_c', 'vertical', [tv('name', 'W_S'), tv('sub', 'W_TM'), KALA, tv('left', 'W_TM'), BAR, ticks(3)], MATCH + ' android:gravity="center_vertical"')))
    # Day & night 4x2; a tall one adds the six parts and the sun
    sun = lin('sun', 'horizontal', sum([[tv('s%dl' % i, 'W_T2'), tv('s%dt' % i, 'W_S', 'android:fontFeatureSettings="tnum"')] + ([FILL] if i < 2 else []) for i in range(3)], []), ROWW)
    write('layout/w2_day_m.xml', root(lin('w_c', 'vertical', [
        lin('hd', 'horizontal', [lin('col_l', 'vertical', [tv('name', 'W_S'), tv('sub', 'W_TM')], 'android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1"'),
                                 lin('col_r', 'vertical', [KALA, tv('left', 'W_TM')], 'android:layout_width="wrap_content" android:layout_height="wrap_content" android:gravity="end"')], ROWW),
        BAR, ticks(4),
        lin('list', 'vertical', [], 'android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"'),
        sun], MATCH + ' android:gravity="center_vertical"')))
    for cur in ('', '_cur'):
        st = 'W_B' if cur else 'W_T'
        write('layout/w2_part_row%s.xml' % cur, lin('p_row', 'horizontal', [tv('p_name', st, 'android:layout_weight="1"').replace('wrap_content" android:layout_height', '0dp" android:layout_height', 1), tv('p_times', st, 'android:fontFeatureSettings="tnum"')],
              NS + ' android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:gravity="center_vertical"'))
    # Calendar 4x4
    wk = lin('wk', 'horizontal', [tv('wd%d' % i, 'W_TM', 'android:layout_weight="1" android:gravity="center" android:textAllCaps="true" android:letterSpacing="0.07"').replace('wrap_content" android:layout_height', '0dp" android:layout_height', 1) for i in range(7)], ROWW)
    nav = lambda i, d: '<ImageView android:id="@+id/%s" android:layout_width="wrap_content" android:layout_height="wrap_content" android:src="@drawable/%s" android:scaleType="center" />' % (i, d)
    card = lin('card', 'vertical', [
        lin('ch', 'horizontal', [tv('cdate', 'W_B', 'android:layout_weight="1"').replace('wrap_content" android:layout_height', '0dp" android:layout_height', 1), tv('badge', 'W_SA')], ROWW + ' android:gravity="center_vertical"'),
        lin('cl2', 'horizontal', [tv('c_st', 'W_BA'), tv('c_until', 'W_TM')], ROWW),
        tv('cl3', 'W_T2'), tv('cl4', 'W_TM')], ROWW)
    write('layout/w2_cal.xml', root(lin('w_c', 'vertical', [
        lin('hd', 'horizontal', [tv('month', 'W_S', 'android:layout_weight="1"').replace('wrap_content" android:layout_height', '0dp" android:layout_height', 1), nav('nav_prev', 'w2_chev_l'), nav('nav_next', 'w2_chev_r')], ROWW + ' android:gravity="center_vertical"'),
        wk,
        lin('grid', 'vertical', [], 'android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"'),
        card,
        lin('nx', 'vertical', [tv('nlab', 'W_TM', 'android:textAllCaps="true" android:letterSpacing="0.09"'), lin('nlist', 'vertical', [], ROWW)], ROWW)], MATCH)))
    # A day of the calendar: the tile (g, a picture so that the gap round it is its padding), over it the column of the number and the
    # moon. The number sits on two halves (hl, hr) that reach the edges of the cell: filled, they join the dates of one Uposatha into a
    # capsule across the cells (WidgetViews.week).
    half = lambda n: '<TextView android:id="@+id/%s" android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1" android:importantForAccessibility="no" />' % n
    num = lambda n, st, more: tv(n, st, 'android:layout_gravity="center" android:gravity="center" android:fontFeatureSettings="tnum"' + more)
    cell = lambda i: ('<FrameLayout android:id="@+id/c%d" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1">' % i +
                      '<ImageView android:id="@+id/g%d" %s android:scaleType="fitXY" android:importantForAccessibility="no" />' % (i, MATCH) +
                      lin('x%d' % i, 'vertical', [
                          '<FrameLayout android:id="@+id/n%d" %s>' % (i, ROWW) +
                          lin('hb%d' % i, 'horizontal', [half('hl%d' % i), half('hr%d' % i)], ROWW + ' android:layout_gravity="center_vertical"') +
                          num('t%d' % i, 'W_T', '') + num('b%d' % i, 'W_B', ' android:visibility="gone"') + '</FrameLayout>',
                          '<ImageView android:id="@+id/m%d" android:layout_width="wrap_content" android:layout_height="wrap_content" android:visibility="gone" android:importantForAccessibility="no" />' % i],
                          MATCH + ' android:gravity="center"') +
                      '<ImageView android:id="@+id/o%d" %s android:scaleType="fitXY" android:visibility="gone" android:importantForAccessibility="no" />' % (i, MATCH) + '</FrameLayout>')
    write('layout/w2_cal_week.xml', lin('week', 'horizontal', [cell(i) for i in range(7)], NS + ' android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1"'))
    write('layout/w2_next_row.xml', lin('n_row', 'horizontal', [
        '<ImageView android:id="@+id/r_moon" android:layout_width="wrap_content" android:layout_height="wrap_content" android:importantForAccessibility="no" />',
        tv('r_date', 'W_S'), tv('r_day', 'W_T2', 'android:layout_weight="1"').replace('wrap_content" android:layout_height', '0dp" android:layout_height', 1), tv('r_in', 'W_TM')],
        NS + ' ' + ROWW + ' android:gravity="center_vertical"'))
    # the three slides of the 4x2 (WidgetViews adds it over the card's bottom): the left half goes back, the right half forward
    img = lambda i, d: '<ImageView android:id="@+id/%s" android:layout_width="wrap_content" android:layout_height="wrap_content" android:src="@drawable/%s" android:importantForAccessibility="no" />' % (i, d)
    write('layout/w2_switch.xml', '<FrameLayout %s android:id="@+id/sw" android:layout_width="match_parent" android:layout_height="44dp" android:layout_gravity="bottom">' % NS +
          lin(None, 'horizontal', ['<FrameLayout android:id="@+id/sw_prev" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" />',
                                   '<FrameLayout android:id="@+id/sw_next" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" />'], MATCH) +
          lin('sw_vis', 'horizontal', [img('sw_l', 'w2_chev_l'), img('sw_d0', 'w2_seg'), img('sw_d1', 'w2_seg'), img('sw_d2', 'w2_seg'), img('sw_r', 'w2_chev_r')],
              'android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_gravity="bottom|center_horizontal" android:gravity="center_vertical"') + '</FrameLayout>')
    # no data yet
    write('layout/w2_ph.xml', root(lin('w_c', 'vertical', [MOON, tv('title', 'W_S', 'android:gravity="center"'), tv('body', 'W_TM', 'android:gravity="center" android:maxLines="2"')], MATCH + ' android:gravity="center"')))
    write('layout/widget_loading.xml', '<FrameLayout %s android:id="@android:id/background" %s><ImageView %s android:scaleType="fitXY" android:src="@drawable/w2_bg" android:importantForAccessibility="no" /></FrameLayout>' % (NS, MATCH, MATCH))


def styles():
    write('values/widget_styles.xml', '''<resources>
    <!-- Text styles of the widgets: one line (cut with an ellipsis only as the last resort: WidgetViews measures every line and scales the
         design so that it fits), Lato in the weights of the design. Sizes and, for a forced theme, colours are set by WidgetViews. -->
    <style name="W_T">
        <item name="android:fontFamily">@font/lato_regular</item>
        <item name="android:textColor">@color/w_text</item>
        <item name="android:maxLines">1</item>
        <item name="android:ellipsize">end</item>
        <item name="android:includeFontPadding">false</item>
    </style>
    <style name="W_T2" parent="W_T"><item name="android:textColor">@color/w_text2</item></style>
    <style name="W_TM" parent="W_T"><item name="android:textColor">@color/w_muted</item></style>
    <style name="W_S" parent="W_T"><item name="android:fontFamily">@font/lato_semibold</item></style>
    <style name="W_SA" parent="W_S"><item name="android:textColor">@color/w_accent_ink</item></style>
    <style name="W_B" parent="W_T"><item name="android:fontFamily">@font/lato_bold</item></style>
    <style name="W_BA" parent="W_B"><item name="android:textColor">@color/w_accent_ink</item></style>
    <!-- the window of a widget's settings (WidgetConfigActivity draws its own content) -->
    <style name="WidgetConfigTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:windowBackground">@color/dg_navbar</item>
        <item name="android:statusBarColor">@color/dg_navbar</item>
        <item name="android:windowLightStatusBar">@bool/dg_light_bar</item>
    </style>
</resources>''')


if __name__ == '__main__':
    colours(); drawables(); styles(); layouts()
    print('written to', RES)
