#!/usr/bin/env python3
"""Generate ios/App/UposathaWidget/WidgetStrings.swift from widget/design/strings.json (+ a few extra keys the iOS widget needs).
Run: python3 widget/tools/gen_ios_strings.py   (re-run after strings.json changes; the output is committed)."""
import json, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = json.load(open(os.path.join(root, 'design', 'strings.json'), encoding='utf-8'))
out = os.path.join(os.path.dirname(root), 'ios', 'App', 'UposathaWidget', 'WidgetStrings.swift')

# Keys the design's strings.json does not have but the native layout needs (kept here, not in the designer's file).
EXTRA = {
    'ru': {
        'until': 'до {time}',
        'kalaShort': 'kala до {time}',
        'vikalaShort': 'vikala до {time}',
        'dayN': '{n}-й день',
        'openApp': 'Открыть Uposatha',
        'today': 'Сегодня',
        'waxing': 'растущая',
        'waning': 'убывающая',
        'noData': 'Откройте приложение, чтобы обновить данные',
        'uposatha.1': 'упосатха', 'uposatha.2': 'упосатхи', 'uposatha.5': 'упосатх',
        'monthsLong': 'Январь|Февраль|Март|Апрель|Май|Июнь|Июль|Август|Сентябрь|Октябрь|Ноябрь|Декабрь',
        'monthsShort': 'янв|фев|мар|апр|мая|июн|июл|авг|сен|окт|ноя|дек',
    },
    'en': {
        'until': 'until {time}',
        'kalaShort': 'kala until {time}',
        'vikalaShort': 'vikala until {time}',
        'dayN': '{n}th day',
        'openApp': 'Open Uposatha',
        'today': 'Today',
        'waxing': 'waxing',
        'waning': 'waning',
        'noData': 'Open the app to refresh the data',
        'uposatha.1': 'Uposatha', 'uposatha.2': 'Uposathas', 'uposatha.5': 'Uposathas',
        'monthsLong': 'January|February|March|April|May|June|July|August|September|October|November|December',
        'monthsShort': 'Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec',
    },
}

def q(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

lines = [
    '// GENERATED by widget/tools/gen_ios_strings.py from widget/design/strings.json. Do not edit by hand.',
    '',
    'enum WidgetStrings {',
    '    static let text: [String: [String: String]] = [',
]
lists = []
for lang in ('ru', 'en'):
    lines.append('        %s: [' % q(lang))
    items = dict(src[lang])
    items.update(EXTRA[lang])
    for k in sorted(items):
        v = items[k]
        if isinstance(v, list):
            lists.append((lang, k, v))
            continue
        lines.append('            %s: %s,' % (q(k), q(v)))
    lines.append('        ],')
lines.append('    ]')
lines.append('')
lines.append('    static let lists: [String: [String: [String]]] = [')
for lang in ('ru', 'en'):
    lines.append('        %s: [' % q(lang))
    for (l, k, v) in lists:
        if l == lang:
            lines.append('            %s: [%s],' % (q(k), ', '.join(q(x) for x in v)))
    lines.append('        ],')
lines.append('    ]')
lines.append('}')
open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('wrote', out)
