// Generates www/index.html from dg-node's search/index.html.
//
// This script is the reason the app's main page can stop being a hand-made copy. It used to be
// copied by hand — build-assets.js's header referenced a "build-page.js" that was never written —
// and by the time the app moved out of dg-node that copy had drifted 147 lines behind the site,
// of which only 4 were intentional. Every one of the other ~143 was a site fix the app shipped
// without.
//
// The real delta between the site's page and the app's page is exactly two edits:
//
//   1. three <script> tags at the very top of <head> — app.js must install its fetch shim before
//      any other script on the page can issue a request, and native-bridge/offline-status hook
//      external links and download progress;
//   2. the service-worker registration block is dropped — there is no dg-light.js here to serve
//      /sw.js, and a SW would only compete with app.js's own fetch interception.
//
// Both are applied here, declaratively, so the page can never drift again.
//
// Anchors: if dg-node's search/index.html carries a `<!-- dg:app-scripts -->` marker we insert
// there; otherwise we insert right after <head>. The marker is the preferred form (it makes the
// insertion point explicit on the site's side) but is deliberately NOT required, so this repo
// builds against an unmodified dg-node checkout.
//
// Usage: node build-page.js

const fs = require('fs');
const path = require('path');
const { WWW, requireNodeRoot, f } = require('./paths');

const APP_SCRIPTS = `<!-- Offline data shim: installs window.fetch interception BEFORE any other script/asset on this
     page can issue a real network request. Everything below is the REAL production page
     (dg-node's search/index.html), generated by build-page.js — reuse the real frontend, only
     swap its data layer, never rebuild the UI. -->
<!-- Native platform first: sets window.dgPlatform (see src/platform.js) so dg-node's browser
     platform.js, loaded right after, is a documented no-op. -->
<script src="/offline/platform.js"></script>
<!-- The "no connection" screen the offline layer raises (src/launch-screens.js). The launch splash is
     the platform's own: Android's animated system splash (res/drawable/dg_splash_icon.xml) and iOS's
     LaunchScreen.storyboard. Here, ahead of the heavy scripts. -->
<script src="/launch-screens.js"></script>
<!-- speechSynthesis over Android TextToSpeech (src/tts.js), before the page's voice player. -->
<script src="/tts.js"></script>
<script src="/offline/app.js"></script>
<script src="/offline/offline-status.js"></script>
<!-- The dhammagift:// scheme, mapped in ONE place for both platforms (src/deep-link.js). Loaded
     before native-bridge.js, which is what asks the native side for incoming URLs and hands them
     to it; see docs/DEEP_LINKS.md for the contract. -->
<script src="/deep-link.js"></script>
<!-- Routes memo/login/mirror-link's external opens through the device's real browser instead of
     this app's own WebView — see native-bridge.js for why plain navigation doesn't work here. -->
<script src="/native-bridge.js"></script>`;

const APP_SCRIPTS_MARKER = '<!-- dg:app-scripts -->';

// The whole <script> element that registers /sw.js, comments included. Matched on its distinctive
// call rather than on surrounding markup so re-indentation on the site's side doesn't break it.
const SW_BLOCK = /\n*<script>(?:(?!<\/script>)[\s\S])*?navigator\.serviceWorker\.register\((?:(?!<\/script>)[\s\S])*?<\/script>/;

const SW_REPLACEMENT = `
<!-- dg-node's service-worker registration is deliberately dropped here (build-page.js): there is
     no dg-light.js serving /sw.js in this app, and a SW would only compete with app.js's own
     fetch shim for the same requests. -->`;

// dg-node's own page already loads the offline layer at the marker (it is the site's PWA layer
// too). The app must not load it twice: two copies of app.js install two fetch shims, two workers
// and two probes over the same OPFS pool. Drop the site's tags and put the app's set (native
// platform first, native-bridge last) in their place — same marker, one set of scripts.
const SITE_OFFLINE_TAGS = /<script src="\/offline\/(?:platform|app|offline-status)\.js"><\/script>\n?/g;

function dropSiteOfflineTags(html) {
    const found = html.match(SITE_OFFLINE_TAGS) || [];
    if (found.length !== 3) {
        throw new Error(
            `search/index.html: expected the site's 3 offline <script> tags, found ${found.length}.\n` +
            'The dg:app-scripts block changed upstream — update SITE_OFFLINE_TAGS, or the app will ' +
            'either miss the offline layer or load it twice.'
        );
    }
    return html.replace(SITE_OFFLINE_TAGS, '');
}

function injectAppScripts(html) {
    if (html.includes(APP_SCRIPTS_MARKER)) {
        return html.replace(APP_SCRIPTS_MARKER, APP_SCRIPTS);
    }
    const head = html.indexOf('<head>');
    if (head === -1) throw new Error('search/index.html: no <head> and no dg:app-scripts marker');
    return html.slice(0, head + '<head>'.length) + '\n' + APP_SCRIPTS + html.slice(head + '<head>'.length);
}

function dropServiceWorker(html) {
    if (!SW_BLOCK.test(html)) {
        throw new Error(
            'search/index.html: service-worker registration block not found.\n' +
            'Either it was removed upstream (drop this step) or its shape changed (update SW_BLOCK).'
        );
    }
    return html.replace(SW_BLOCK, SW_REPLACEMENT);
}

// Cheap guards against a silently wrong page: every intended edit must be observable in the
// output. A page that builds but ships a live SW, or without the fetch shim, is worse than a
// build failure — it fails on the device, offline, where nobody is watching a console.
function verify(html) {
    const problems = [];
    for (const tag of ['/offline/platform.js', '/launch-screens.js', '/offline/app.js', '/offline/offline-status.js', '/native-bridge.js']) {
        const count = html.split(`src="${tag}"`).length - 1;
        if (count === 0) problems.push(`missing <script src="${tag}">`);
        else if (count > 1) problems.push(`duplicate <script src="${tag}"> (${count}x) — the offline layer would load twice`);
    }
    if (html.includes('serviceWorker.register')) problems.push('service worker registration still present');
    if (!html.includes('viewport-fit=cover')) problems.push('viewport is not viewport-fit=cover — the page would not reach under the system bars');
    if (/href="\/settings\/"/.test(html)) problems.push('href="/settings/" survived — Settings would open the search page');
    if (html.indexOf('src="/offline/platform.js"') > html.indexOf('<script src="/assets/')) {
        problems.push('offline platform.js is not the first script — the fetch shim would install too late');
    }
    if (problems.length) throw new Error(`build-page.js produced a bad page:\n  - ${problems.join('\n  - ')}`);
}

// The site links to its own sub-pages as directories — href="/settings/". A web server resolves
// that to settings/index.html; Capacitor's asset server does not, and an unresolved path there
// falls back to the root index.html. So tapping the gear loaded the SEARCH page at the address
// /settings/, the SPA router read "settings" as a keyword, and the reader got a failed search for
// the word instead of their settings. There was no way into Settings at all.
//
// Pointing at the file directly is what makes it resolve. The site keeps the directory form,
// which is the nicer URL and works there; only the app build is rewritten.
const DIRECTORY_LINKS = /href="\/(settings|memo)\/"/g;

// Edge to edge (owner, dg-apps#40: no painted "beard" round the page): viewport-fit=cover lets the
// page run under the transparent status and gesture bars — Capacitor's SystemBars passes the insets
// through to it instead of padding the WebView and showing the window background there. The page
// keeps clear of the bars itself (html.dg-app, dg-node search/css/home.css). App build only: on the
// site the meta stays as it is.
const VIEWPORT = '<meta name="viewport" content="width=device-width, initial-scale=1">';
function coverViewport(html) {
    if (!html.includes(VIEWPORT)) throw new Error('search/index.html: viewport meta not found — update VIEWPORT in build-page.js');
    return html.replace(VIEWPORT, '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">');
}

function resolveDirectoryLinks(html) {
    let count = 0;
    const out = html.replace(DIRECTORY_LINKS, (_, dir) => { count++; return `href="/${dir}/index.html"`; });
    if (!count) {
        throw new Error(
            'build-page.js: no directory-style links found in search/index.html.\n' +
            'Either they were rewritten upstream (drop this step) or their shape changed ' +
            '(update DIRECTORY_LINKS) — leaving them makes Settings unreachable in the app.'
        );
    }
    console.log(`  directory links resolved to index.html: ${count}`);
    return out;
}

function main() {
    requireNodeRoot();
    const src = f('search/index.html');
    let html = fs.readFileSync(src, 'utf8');
    const before = html.length;

    html = dropSiteOfflineTags(html);
    html = injectAppScripts(html);
    html = dropServiceWorker(html);
    html = resolveDirectoryLinks(html);
    html = coverViewport(html);
    verify(html);

    fs.mkdirSync(WWW, { recursive: true });
    const dest = path.join(WWW, 'index.html');
    fs.writeFileSync(dest, html, 'utf8');
    console.log(`Page: ${path.relative(process.cwd(), dest)} <- ${src} (${before} -> ${html.length} bytes)`);
}

main();
