package gift.dhamma.uposatha;

import android.content.Context;
import android.content.res.Configuration;
import android.graphics.Bitmap;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.os.Build;
import android.util.TypedValue;
import android.view.View;
import android.widget.RemoteViews;

import androidx.core.content.res.ResourcesCompat;

import org.json.JSONObject;

import java.util.List;
import java.util.Locale;

import static gift.dhamma.uposatha.WidgetConfig.*;

/**
 * Builds a widget as REAL views (texts are TextViews in Lato; the only pictures are the moon and the day bar).
 *
 * Seven widgets, each one design (WidgetPlan.MOON .. CAL). A design is written here in "base dp": the sizes of its smallest cell.
 * For the cell the launcher gives, every line is measured with the real font, the design's width and height are summed up, and the
 * whole design is scaled by k = how many times it fits (WidgetPlan.scale): a bigger cell shows the SAME widget bigger, a smaller one
 * smaller; nothing is cut and a big cell is not left with small text. The layouts (res/layout/w2_*.xml, generated by
 * widget/tools/gen_android_res.py) hold only the structure; every text size, padding and picture is set here, times k.
 *
 * Colours: with the theme "system" the views carry colour RESOURCES (values / values-night), so the launcher recolours the widget
 * by itself when the system theme changes; with a forced theme (the widget's own setting) fixed colours are set.
 * Nothing here computes the moon, the sun or an Uposatha: WidgetModel lays out what the page handed over.
 */
final class WidgetViews {
    /** Bytes of the pictures handed to RemoteViews since the counter was last reset (the launcher refuses an update that carries too much). */
    static long bitmapBytes;

    private static final int RG = 0, SB = 1, BD = 2;   // Lato regular, semibold, bold
    private static final int[] WD = { R.id.wd0, R.id.wd1, R.id.wd2, R.id.wd3, R.id.wd4, R.id.wd5, R.id.wd6 };
    private static final int[] CELL = { R.id.c0, R.id.c1, R.id.c2, R.id.c3, R.id.c4, R.id.c5, R.id.c6 };
    private static final int[] CG = { R.id.g0, R.id.g1, R.id.g2, R.id.g3, R.id.g4, R.id.g5, R.id.g6 };   // the tile
    private static final int[] HL = { R.id.hl0, R.id.hl1, R.id.hl2, R.id.hl3, R.id.hl4, R.id.hl5, R.id.hl6 };   // the left and the right half of the band behind a number
    private static final int[] CO = { R.id.o0, R.id.o1, R.id.o2, R.id.o3, R.id.o4, R.id.o5, R.id.o6 };   // today's frame, over everything in the cell
    private static final int[] HR = { R.id.hr0, R.id.hr1, R.id.hr2, R.id.hr3, R.id.hr4, R.id.hr5, R.id.hr6 };
    private static final int[] CT = { R.id.t0, R.id.t1, R.id.t2, R.id.t3, R.id.t4, R.id.t5, R.id.t6 };
    private static final int[] CB = { R.id.b0, R.id.b1, R.id.b2, R.id.b3, R.id.b4, R.id.b5, R.id.b6 };
    private static final int[] CM = { R.id.m0, R.id.m1, R.id.m2, R.id.m3, R.id.m4, R.id.m5, R.id.m6 };
    /** Drawables by theme (system: colour resources with a night variant; light; dark): explicit, so the resource shrinker sees them used. */
    private static final int TILE = 0, TILE_DAY = 1, TILE_TODAY = 2, CARD = 3, BADGE = 4, PLATE = 5, RING = 6;
    private static final int[][] BG = {
            { R.drawable.w2_tile, R.drawable.w2_tile_lt, R.drawable.w2_tile_dk },
            { R.drawable.w2_tile_day, R.drawable.w2_tile_day_lt, R.drawable.w2_tile_day_dk },
            { R.drawable.w2_tile_today, R.drawable.w2_tile_today_lt, R.drawable.w2_tile_today_dk },
            { R.drawable.w2_card, R.drawable.w2_card_lt, R.drawable.w2_card_dk },
            { R.drawable.w2_badge, R.drawable.w2_badge_lt, R.drawable.w2_badge_dk },
            { R.drawable.w2_plate, R.drawable.w2_plate_lt, R.drawable.w2_plate_dk },
            { R.drawable.w2_ring, R.drawable.w2_ring_lt, R.drawable.w2_ring_dk } };

    private final Context ctx;
    private final int widgetId, kind, monthOff, theme, slide;   // slide: 0..2 on the 4x2 with the three slides, else -1
    private static final float SWITCH_DP = 22;   // the room the slides' switch takes at the bottom (real dp, not scaled)
    private final float w, h, density;          // the cell in dp (a little less than reported: a launcher may round up)
    private final boolean night;
    private final WidgetConfig cfg;
    private RemoteViews rv;
    private WidgetModel m;
    private WidgetText tx;
    private float k = 1;                        // the scale of the design in this cell

    private final int drawnW, drawnH;   // the size (dp) this view is drawn for; the height: the taps of its switch and arrows carry it (WidgetProvider.slide)

    private WidgetViews(Context ctx, int widgetId, int kind, int wDp, int hDp, WidgetConfig cfg, int monthOff, int slide) {
        this.ctx = ctx; this.widgetId = widgetId; this.cfg = cfg; this.monthOff = monthOff; this.slide = slide; this.drawnW = wDp; this.drawnH = hDp;
        this.w = Math.max(40, wDp - 2); this.h = Math.max(40, hDp - 2 - (slide >= 0 ? SWITCH_DP : 0));
        // a big widget (4x2, 4x4) with slides is one of three designs at the widget's own size: its own (the 2x2's in a narrow cell), Day & night, the calendar
        this.kind = slide < 0 ? kind : slide == 1 ? WidgetPlan.DAY : slide == 2 ? WidgetPlan.CAL : this.w < 200 ? WidgetPlan.UPO : WidgetPlan.UPO_M;
        this.density = ctx.getResources().getDisplayMetrics().density;
        this.theme = cfg.theme;
        this.night = (ctx.getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK) == Configuration.UI_MODE_NIGHT_YES;
    }

    /** The widget of a kind for one cell size; data == null, stale or not covering today: the placeholder. A failure falls back to the placeholder too. */
    static RemoteViews build(Context ctx, int widgetId, int kind, int wDp, int hDp, JSONObject data, long now, WidgetConfig cfg, int monthOff, int slide) {
        if (cfg == null) cfg = new WidgetConfig();
        if ((kind != WidgetPlan.UPO_M && kind != WidgetPlan.CAL) || !cfg.slides) slide = -1;
        else slide = ((slide % 3) + 3) % 3;
        WidgetViews v = new WidgetViews(ctx, widgetId, kind, wDp, hDp, cfg, monthOff, slide);
        WidgetModel model = WidgetModel.parse(data, now);
        if (model != null) {
            try {
                v.m = model;
                v.tx = new WidgetText(ctx, model.lang);
                if (v.fill()) return v.rv;
            } catch (RuntimeException e) {
                android.util.Log.w("DgWidget", "layout failed, placeholder instead: " + e);
            }
        }
        v.m = null;
        v.placeholder(data);
        return v.rv;
    }

    private boolean fill() {
        switch (kind) {
            case WidgetPlan.MOON: moonOnly(); break;
            case WidgetPlan.MOONUPO: moonUpo(); break;
            case WidgetPlan.UPO: upo(); break;
            case WidgetPlan.STRIP: strip(); break;
            case WidgetPlan.UPO_M: upoM(); break;
            case WidgetPlan.DAY: if (!dayNight()) return false; break;
            default: calendar();
        }
        frame(WidgetProvider.route(kind, null));
        return true;
    }

    // ------------------------------------------------------------------ small helpers

    private void start(int layout) { rv = new RemoteViews(ctx.getPackageName(), layout); }
    private int px(float baseDp) { return Math.round(baseDp * k * density); }
    private void show(int id, boolean on) { rv.setViewVisibility(id, on ? View.VISIBLE : View.GONE); }
    private void pad(int id, float l, float t, float r, float b) { rv.setViewPadding(id, px(l), px(t), px(r), px(b) + (id == R.id.w_c && slide >= 0 ? Math.round(SWITCH_DP * density) : 0)); }
    private static float lh(float size) { return size * 1.2f; }   // the height of a line of Lato without the font padding
    private static float max(float... v) { float x = 0; for (float f : v) x = Math.max(x, f); return x; }

    private void text(int id, CharSequence s, float size, int role) { text(rv, id, s, size, role); }
    private void text(RemoteViews r, int id, CharSequence s, float size, int role) {
        r.setTextViewText(id, s);
        r.setTextViewTextSize(id, TypedValue.COMPLEX_UNIT_DIP, size * k);
        tint(r, id, role);
    }

    /** The colour of a text by its role: fixed for a forced theme; else a resource the launcher resolves itself (API 31+), or the colour of now. */
    private void tint(RemoteViews r, int id, int role) {
        if (theme != SYSTEM) r.setTextColor(id, forced()[role]);
        else if (Build.VERSION.SDK_INT >= 31) r.setColor(id, "setTextColor", RES_C[role]);
        else r.setTextColor(id, ctx.getColor(RES_C[role]));
    }
    private void tintImage(int id, int role) { tintImage(rv, id, role); }
    private void tintImage(RemoteViews r, int id, int role) {
        if (theme != SYSTEM) r.setInt(id, "setColorFilter", forced()[role]);
        else if (Build.VERSION.SDK_INT >= 31) r.setColor(id, "setColorFilter", RES_C[role]);
        else r.setInt(id, "setColorFilter", ctx.getColor(RES_C[role]));
    }
    private int[] forced() { return theme == DARK ? DARK_C : LIGHT_C; }
    private int bg(int which) { return BG[which][theme]; }

    private void frame(String route) {
        rv.setOnClickPendingIntent(android.R.id.background, WidgetProvider.openApp(ctx, widgetId, 0, route));
        // no content description on the card: a screen reader then reads the widget's own lines (a fixed "Uposatha widget" would hide them)
        // A launcher draws a new RemoteViews ONTO the views it already has when the layout is the same (reapply): whatever one state sets,
        // the other state must set back, and a view that is added must be taken out first. Found on a device, 2026-10-10: the Moon's
        // percent stayed hidden after it was turned on, and every redraw left one more copy of the slides' switch in the launcher.
        rv.setInt(R.id.w_bg, "setColorFilter", theme != SYSTEM ? forced()[SURFACE] : 0);   // 0: a filter that changes nothing
        rv.setInt(R.id.w_bg, "setImageAlpha", Math.round(cfg.opacity * 2.55f));
        rv.removeAllViews(R.id.sw_host);
        if ((ctx.getApplicationInfo().flags & android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE) != 0) rv.setContentDescription(R.id.sw_host, "drawn for " + drawnW + "x" + drawnH);   // which of the sizes the launcher took (the device test reads it)
        if (slide >= 0) {   // the switch of the three slides: the dots show where we are; the left half of the strip goes back, the right half forward
            RemoteViews sw = new RemoteViews(ctx.getPackageName(), R.layout.w2_switch);
            int[] dots = { R.id.sw_d0, R.id.sw_d1, R.id.sw_d2 };
            int dp = Math.round(density);
            for (int i = 0; i < 3; i++) { tintImage(sw, dots[i], i == slide ? ACCENT : EDGE); sw.setViewPadding(dots[i], 3 * dp, 0, 3 * dp, 0); }
            tintImage(sw, R.id.sw_l, MUTED); tintImage(sw, R.id.sw_r, MUTED);
            sw.setViewPadding(R.id.sw_vis, 0, 0, 0, 3 * dp);
            sw.setOnClickPendingIntent(R.id.sw_prev, WidgetProvider.slide(ctx, widgetId, -1, drawnH));
            sw.setOnClickPendingIntent(R.id.sw_next, WidgetProvider.slide(ctx, widgetId, 1, drawnH));
            rv.addView(R.id.sw_host, sw);
        }
    }

    // ------------------------------------------------------------------ measuring with the real font

    private static Typeface[] fonts;
    private static final Paint MP = new Paint(Paint.ANTI_ALIAS_FLAG);

    private Typeface font(int f) {
        if (fonts == null) {
            Typeface[] t = new Typeface[3];
            int[] res = { R.font.lato_regular, R.font.lato_semibold, R.font.lato_bold };
            for (int i = 0; i < 3; i++) {
                try { t[i] = ResourcesCompat.getFont(ctx, res[i]); } catch (RuntimeException e) { t[i] = null; }
                if (t[i] == null) t[i] = i == 0 ? Typeface.DEFAULT : Typeface.DEFAULT_BOLD;
            }
            fonts = t;
        }
        return fonts[f];
    }

    /** The width of a text in base dp at a size in base dp. */
    private float mw(int f, float size, String s) { return mw(f, size, s, false); }
    private float mw(int f, float size, String s, boolean tnum) {
        if (s == null || s.isEmpty()) return 0;
        synchronized (MP) {
            MP.setTypeface(font(f));
            MP.setTextSize(size * 8);
            MP.setFontFeatureSettings(tnum ? "tnum" : null);
            return MP.measureText(s) / 8f;
        }
    }

    private void fit(float needW, float needH, float min, float max) { k = WidgetPlan.scale(w, h, needW * 1.03f, needH, min, max); }

    // ------------------------------------------------------------------ the words (one table for every widget)

    private String wd(String ymd) { return tx.weekday(WidgetFormat.dow(WidgetFormat.year(ymd), WidgetFormat.month(ymd), WidgetFormat.day(ymd))); }
    /** "Sat 17 Oct" / "сб 17 окт". */
    private String dateLabel(String ymd) { return wd(ymd) + " " + WidgetFormat.day(ymd) + " " + tx.monthShort(WidgetFormat.month(ymd)); }
    private String dayN(WidgetModel.Upo u) { return tx.fmt("w.dayN", "n", u.lunarDay); }
    private String state() { return tx.get(m.ongoing ? "now" : "w.coming"); }
    private String status(WidgetModel.Upo u) { return dayN(u) + " · " + state(); }
    /** The date the counter runs to: the evening the Uposatha begins on, or, when it is on, the day it ends. */
    private String whenDate(WidgetModel.Upo u) { return dateLabel(m.ongoing ? u.end.ymd : u.start.ymd); }
    private String whenTime(WidgetModel.Upo u) { return m.ongoing ? tx.fmt("w.until", "time", u.end.hm) : tx.fmt("w.from", "time", u.start.hm); }
    /** "0.11", "0,11" in Russian: the lit percent with two decimals, as the page shows it. */
    private String lit() {
        String s = String.format(java.util.Locale.US, "%.2f", m.litNow);
        return tx.ru() ? s.replace('.', ',') : s;
    }
    private String phaseName() { return tx.get("w.ph" + WidgetPlan.phaseIndex(m.moonNow)); }
    /** "waxing crescent · 30%": the moon as it is NOW (not the phase of the Uposatha the counter runs to). */
    private String moonLine() { return phaseName() + " · " + lit() + "%"; }
    /** With details: what comes after: the end of an Uposatha that is coming, or the next one when one is on. */
    private String detailLine(WidgetModel.Upo u) {
        if (!m.ongoing) return tx.fmt("w.ends", "day", dateLabel(u.end.ymd), "time", u.end.hm);
        List<WidgetModel.Upo> nx = m.following(1);
        return nx.isEmpty() ? "" : tx.fmt("w.next", "n", tx.fmt("w.ord", "n", nx.get(0).lunarDay), "day", dateLabel(nx.get(0).start.ymd));
    }
    private boolean det() { return WidgetConfig.pick(cfg.details, m.detail); }
    private boolean kalaOn() { return m.kala != WidgetModel.NONE && WidgetConfig.pick(cfg.kala, m.showKala); }

    /** "через 8 д" / "in 8 d" for a later Uposatha. */
    private String inText(WidgetModel.Upo n) {
        long rem = n.start.ms - m.now, days = rem / WidgetFormat.DAY;
        if (days >= 1) return tx.fmt("inDays", "n", days);
        String in = tx.get("inDays");
        return in.substring(0, in.indexOf("{n}")) + WidgetFormat.counter(Math.max(0, rem), tx.get("unit.d"), tx.get("unit.h"));   // under a day: "через 2 ч", not "через 0 д"
    }

    // ------------------------------------------------------------------ the pieces every design is made of

    private static float box(float disc) { return disc / WidgetMoon.DISC; }
    /** The transparent margin of the moon's picture (the halo's room) on each side: rows under the moon are moved in by it, so their left edge is the disc's. */
    private static float inset(float disc) { return (box(disc) - disc) / 2; }

    /** The moon of the widget (ids moon_l / moon_d: the pair the system theme picks from; moon_x: the one of a forced theme). disc in base dp. */
    private void moon(float disc, double phase) {
        float boxDp = box(disc) * k;
        boolean south = m != null && m.south;
        if (theme == SYSTEM) {
            Bitmap l = WidgetMoon.render(ctx, boxDp, phase, south, false), d = WidgetMoon.render(ctx, boxDp, phase, south, true);
            bitmapBytes += l.getByteCount() + d.getByteCount();
            rv.setImageViewBitmap(R.id.moon_l, l);
            rv.setImageViewBitmap(R.id.moon_d, d);
            show(R.id.moon_x, false); show(R.id.moon_l, true); show(R.id.moon_d, true);
        } else {
            Bitmap x = WidgetMoon.render(ctx, boxDp, phase, south, theme == DARK);
            bitmapBytes += x.getByteCount();
            rv.setImageViewBitmap(R.id.moon_x, x);
            show(R.id.moon_x, true); show(R.id.moon_l, false); show(R.id.moon_d, false);
        }
    }

    private Bitmap mini(float sizeDp, double phase) {
        Bitmap b = WidgetMoon.renderMini(ctx, sizeDp * k, phase, m.south);
        bitmapBytes += b.getByteCount();
        return b;
    }

    /** "30% ↑": how much of the moon is lit, and whether it is growing. */
    private float pctW(float size) { return mw(SB, size, lit() + "%") + size * 0.8f; }
    private void pct(float size, int role) {
        text(R.id.pc, lit() + "%", size, role);
        text(R.id.pc_ar, m.moonNow < 0.5 ? " ↑" : " ↓", size * 0.8f, MUTED);
    }

    /** The counter "1d 7h": the digits big, the units small beside them. */
    private float counterW(float size, long rem) {
        long[] dh = WidgetPlan.counter(rem);
        float u = size * 0.42f, wd = 0;
        if (dh[0] > 0) wd += mw(RG, size, String.valueOf(dh[0]), true) + size * 0.05f + mw(SB, u, tx.get("unit.d")) + size * 0.17f;
        return wd + mw(RG, size, String.valueOf(dh[1]), true) + size * 0.05f + mw(SB, u, tx.get("unit.h"));
    }
    private void counter(float size, long rem) {
        long[] dh = WidgetPlan.counter(rem);
        float u = size * 0.42f;
        text(R.id.c_dn, String.valueOf(dh[0]), size, TEXT); text(R.id.c_du, tx.get("unit.d"), u, TEXT);
        text(R.id.c_hn, String.valueOf(dh[1]), size, TEXT); text(R.id.c_hu, tx.get("unit.h"), u, TEXT);
        pad(R.id.c_du, size * 0.05f, 0, size * 0.17f, 0);
        pad(R.id.c_hu, size * 0.05f, 0, 0, 0);
        show(R.id.c_dn, dh[0] > 0); show(R.id.c_du, dh[0] > 0);
    }

    /** "Kala until 12:41" (green) / "Vikala until 05:50" (red): the same words on every widget. */
    private String kalaWord() { return tx.get(m.kala == WidgetModel.VIKALA ? "w.vikala" : "w.kala"); }
    private float kalaW(float size) { return mw(BD, size, kalaWord()) + mw(RG, size, tx.get("w.untilMid")) + mw(BD, size, m.kalaEndHm, true); }
    private void kala(float size) {
        int accent = m.kala == WidgetModel.VIKALA ? VIK : INK;
        text(R.id.k_word, kalaWord(), size, accent);
        text(R.id.k_mid, tx.get("w.untilMid"), size, TEXT);
        text(R.id.k_time, m.kalaEndHm, size, accent);
    }
    private String kalaLeft() { return tx.fmt("kalaLeft", "left", WidgetFormat.left(m.kalaEndMs - m.now, tx.get("unit.h"), tx.unitMin())); }

    // ================================================================== Moon 1x1

    private void moonOnly() {
        final float D = 44, PS = 13;
        if (!cfg.pct) {   // just the moon; a screen reader still hears the phase and the percent
            fit(8 + box(D), 8 + box(D), 0.6f, 8f);   // just a moon: as big as the cell, whatever the cell
            start(R.layout.w2_moon);
            moon(D, m.moonNow);
            show(R.id.pc_row, false);
            rv.setContentDescription(R.id.w_c, tx.get("w.ph" + WidgetPlan.phaseIndex(m.moonNow)) + ", " + lit() + "%");
            return;
        }
        fit(12 + max(box(D), pctW(PS)), 12 + box(D) + 1 + lh(PS), 0.6f, 8f);
        start(R.layout.w2_moon);
        moon(D, m.moonNow);
        show(R.id.pc_row, true);
        rv.setContentDescription(R.id.w_c, null);
        pct(PS, TEXT);
        pad(R.id.pc_row, 0, 1, 0, 0);
    }

    // ================================================================== Moon + Uposatha 2x1

    private void moonUpo() {
        WidgetModel.Upo u = m.cur();
        long rem = m.counterTarget() - m.now;
        final float D = 40, PS = 13, CS = 24;
        String day = dayN(u), st = state();
        float left = max(box(D), pctW(PS)), right = max(mw(BD, 12.5f, day), counterW(CS, rem), mw(RG, 11, st));
        fit(16 + left + 6 + right, 16 + max(box(D) + 1 + lh(PS), lh(12.5f) + lh(CS) + lh(11)), 0.6f, 2.4f);
        start(R.layout.w2_moonupo);
        moon(D, m.moonNow);
        pct(PS, TEXT);
        pad(R.id.pc_row, 0, 1, 0, 0);
        pad(R.id.col_r, 6, 0, 0, 0);
        text(R.id.nday, day, 12.5f, INK);
        counter(CS, rem);
        text(R.id.state, st, 11, MUTED);
    }

    // ================================================================== Uposatha 2x2 (the agreed 1A / 1B)

    private void upo() {
        WidgetModel.Upo u = m.cur();
        long rem = m.counterTarget() - m.now;
        boolean det = det(), kala = kalaOn();
        final float CS = 34, T = 11.5f, ST = 12.5f, G = 3;
        String day = dayN(u), st = state(), date = whenDate(u), time = whenTime(u), ml = moonLine(), ph = phaseName();
        float cntW = counterW(CS, rem), kW = kala ? kalaW(ST) : 0, dtW = mw(SB, T, date), tmW = mw(RG, T, time), stMax = max(mw(BD, ST, day), mw(BD, ST, st));
        float tail = (det ? G + lh(T) : 0) + (kala ? G + lh(ST) : 0);
        int gaps = 1 + (det ? 1 : 0) + (kala ? 1 : 0);
        // Three arrangements of the same lines; the one that can be drawn biggest in this cell is taken (WidgetPlan.upoArrangement).
        // 0: wide, the agreed arrangement: the day beside the moon, the date and time at the right of the counter
        float in0 = inset(44), w0 = 24 + max(box(44) - in0 + 5 + mw(BD, ST, day + " · " + st), cntW + 8 + max(dtW, tmW), det ? mw(RG, T, ml) : 0, kW);
        float h0 = 24 + box(44) + G + lh(CS) + tail;
        // 1: stacked, the date and time in one line under the counter
        float in1 = inset(40), w1 = 24 + max(box(40) - in1 + 6 + stMax, cntW, dtW + mw(RG, T, " ") + tmW, det ? mw(RG, T, ml) : 0, kW);
        float h1 = 24 + box(40) + G + lh(CS) + 1 + lh(T) + tail;
        // 2: stacked, a narrow cell: the date and the time in two lines; with details the percent under the moon and the phase's name alone
        float in2 = inset(38), w2 = 24 + max(max(box(38), det ? pctW(T) : 0) - in2 + 6 + stMax, cntW, dtW, tmW, det ? mw(RG, T, ph) : 0, kW);
        float h2 = 24 + box(38) + (det ? 1 + lh(T) : 0) + G + lh(CS) + 1 + 2 * lh(T) + tail;
        int arr = WidgetPlan.upoArrangement(WidgetPlan.scale(w, h, w0 * 1.03f, h0, 0.1f, 9), WidgetPlan.scale(w, h, w1 * 1.03f, h1, 0.1f, 9), WidgetPlan.scale(w, h, w2 * 1.03f, h2, 0.1f, 9));
        float needH = arr == 0 ? h0 : arr == 1 ? h1 : h2, in = arr == 0 ? in0 : arr == 1 ? in1 : in2;
        fit(arr == 0 ? w0 : arr == 1 ? w1 : w2, needH, 0.75f, 2.2f);
        float g = WidgetPlan.gap(h, k, needH, gaps, G, 12);
        start(arr == 0 ? R.layout.w2_upo_wide : R.layout.w2_upo_stack);
        pad(R.id.w_c, 12 - in, 12, 12, 12);
        if (arr == 0) {
            moon(44, m.moonNow);
            text(R.id.st, day + " · " + st, ST, INK);
            pad(R.id.st, 5, 0, 0, 0);
            pad(R.id.r2, in, g, 0, 0);
            counter(CS, rem);
            text(R.id.dt, date, T, TEXT);
            text(R.id.tm, time, T, MUTED);
            pad(R.id.when, 0, 0, 0, CS * 0.14f);   // the two lines sit on the counter's baseline, not under its descent
        } else {
            moon(arr == 1 ? 40 : 38, m.moonNow);
            boolean pc = arr == 2 && det;
            show(R.id.pc_row, pc);
            if (pc) { pct(T, TEXT); pad(R.id.pc_row, 0, 1, 0, 0); }
            text(R.id.st1, day, ST, INK);
            text(R.id.st2, st, ST, INK);
            pad(R.id.col_st, 6, 0, 0, 0);
            pad(R.id.cnt, in, g, 0, 0);
            counter(CS, rem);
            show(R.id.when_a, arr == 1); show(R.id.when_b, arr == 2);
            if (arr == 1) { text(R.id.dt_a, date, T, TEXT); text(R.id.tm_a, " " + time, T, MUTED); pad(R.id.when_a, in, 1, 0, 0); }
            else { text(R.id.dt_b, date, T, TEXT); text(R.id.tm_b, time, T, MUTED); pad(R.id.when_b, in, 1, 0, 0); }
        }
        show(R.id.ml, det);
        if (det) { text(R.id.ml, arr == 2 ? ph : ml, T, MUTED); pad(R.id.ml, in, g, 0, 0); }
        show(R.id.kala, kala);
        if (kala) { kala(ST); pad(R.id.kala, in, g, 0, 0); }
    }

    // ================================================================== Uposatha 4x1

    private void strip() {
        WidgetModel.Upo u = m.cur();
        long rem = m.counterTarget() - m.now;
        boolean kala = kalaOn();
        String st = status(u), date = whenDate(u), time = whenTime(u);
        // (A) the 4x1 as agreed: the moon and three lines beside it
        final float D = 60, CS = 30, T = 11.5f, ST = 12.5f;
        float in = inset(D);
        float col = max(mw(BD, ST, st) + 10 + pctW(T), counterW(CS, rem) + 10 + max(mw(SB, T, date), mw(RG, T, time)), kala ? kalaW(ST) : 0);
        float needW = 24 - in + box(D) + 8 - in + col, needH = 16 + max(box(D), lh(ST) + 1 + lh(CS) + (kala ? 1 + lh(ST) : 0));
        // (B) a low wide cell (the owner's launcher: a row is 75 dp, so 4 x 1 is 313 x 75 and 5 x 1 is 391 x 75): the moon, the counter
        // as high as the moon, and three lines beside it. Lower for the same type, so the lines come out bigger and the width is used
        // (owner, 2026-10-10: "a lot of room and small type").
        final float D2 = 54, CS2 = 40, ST2 = 15, T2 = 13.5f;
        float in2 = inset(D2);
        float colB = max(mw(BD, ST2, st) + 10 + pctW(T2), mw(SB, T2, date) + 7 + mw(RG, T2, time), kala ? kalaW(T2) : 0);
        float needW2 = 24 - in2 + box(D2) + 8 - in2 + counterW(CS2, rem) + 14 + colB;
        float needH2 = 14 + max(box(D2), lh(CS2), lh(ST2) + 1 + lh(T2) + (kala ? 1 + lh(T2) : 0));
        float kA = WidgetPlan.scale(w, h, needW * 1.03f, needH, 0.6f, 2.2f), kB = WidgetPlan.scale(w, h, needW2 * 1.03f, needH2, 0.6f, 2.6f);
        if (kB * ST2 > kA * ST) {   // the arrangement whose lines come out bigger
            fit(needW2, needH2, 0.6f, 2.6f);
            start(R.layout.w2_strip_w);
            pad(R.id.w_c, 12 - in2, 7, 12, 7);
            moon(D2, m.moonNow);
            pad(R.id.cnt, 8 - in2, 0, 0, 0);
            counter(CS2, rem);
            pad(R.id.col_r, 14, 0, 0, 0);
            text(R.id.st, st, ST2, INK);
            pct(T2, MUTED);
            text(R.id.dt, date, T2, TEXT);
            text(R.id.tm, time, T2, MUTED);
            pad(R.id.tm, 7, 0, 0, 0);
            pad(R.id.l2, 0, 1, 0, 0);
            show(R.id.kala, kala);
            if (kala) { kala(T2); pad(R.id.kala, 0, 1, 0, 0); }
            return;
        }
        fit(needW, needH, 0.6f, 2.2f);
        start(R.layout.w2_strip);
        pad(R.id.w_c, 12 - in, 8, 12, 8);
        moon(D, m.moonNow);
        pad(R.id.col_r, 8 - in, 0, 0, 0);
        text(R.id.st, st, ST, INK);
        pct(T, MUTED);
        pad(R.id.r2, 0, 1, 0, 0);
        counter(CS, rem);
        text(R.id.dt, date, T, TEXT);
        text(R.id.tm, time, T, MUTED);
        pad(R.id.when, 10, 0, 0, CS * 0.14f);
        show(R.id.kala, kala);
        if (kala) { kala(ST); pad(R.id.kala, 0, 1, 0, 0); }
    }

    // ================================================================== Uposatha 4x2

    private void upoM() {
        WidgetModel.Upo u = m.cur();
        long rem = m.counterTarget() - m.now;
        boolean det = det(), kala = kalaOn();
        final float D = 80, CS = 40, T = 13, ST = 14, KS = 13.5f;
        String st = status(u), date = whenDate(u), time = whenTime(u), ml = moonLine(), dl = det ? detailLine(u) : "";
        if (dl.isEmpty()) det = false;
        float in = inset(D);
        float col = max(mw(BD, ST, st), counterW(CS, rem) + 12 + max(mw(SB, T, date), mw(RG, T, time)), mw(RG, T, ml), det ? mw(RG, T, dl) : 0, kala ? kalaW(KS) : 0);
        float colH = lh(ST) + 4 + lh(CS) + 4 + lh(T) + (det ? 2 + lh(T) : 0) + (kala ? 5 + lh(KS) : 0);
        float needW = 28 - in + box(D) + 12 - in + col, heroH = max(box(D), colH);
        // a tall cell (the Uposatha slide of the big widget): the block at the top, then the next Uposathas and the sun of today, so the height is used
        final float SUN = 8 + lh(12), LIST = 10 + 16;
        float kTall = WidgetPlan.scale(w, h, needW * 1.03f, 24 + heroH + LIST + 2 * 26 + SUN, 0.6f, 1.6f);
        boolean tall = kTall >= 1f && h / kTall - (24 + heroH + LIST + SUN) >= 2 * 26;
        if (tall) k = kTall; else fit(needW, 24 + heroH, 0.6f, 2.2f);
        start(tall ? R.layout.w2_upo_l : R.layout.w2_upo_m);
        pad(R.id.w_c, 14 - in, tall ? 14 : 12, 14, 12);
        if (tall) {
            int rows = (int) Math.min(8, Math.floor((h / k - 26 - heroH - LIST - SUN) / 26));
            pad(R.id.nx, in, 10, 0, 0);
            float spare = h / k - 26 - heroH - LIST - SUN - rows * 26;   // what is still left is shared by the rows, so the sun sits right under the list
            boolean any = nextRows(rows, rows > 0 ? Math.min(10, spare / rows) / 2 : 0);
            show(R.id.nx, true);
            show(R.id.nlab, any);
            WidgetModel.Day d = m.dayIdx >= 0 ? m.days.get(m.dayIdx) : null;
            show(R.id.sun, d != null);
            if (d != null) {
                String[][] sun = { { tx.get("sunrise"), d.sunrise.hm }, { tx.get("noon"), d.noon.hm }, { tx.get("sunset"), d.sunset.hm } };
                int[][] ids = { { R.id.s0l, R.id.s0t }, { R.id.s1l, R.id.s1t }, { R.id.s2l, R.id.s2t } };
                for (int i = 0; i < 3; i++) { text(ids[i][0], sun[i][0] + " ", 12, TEXT2); text(ids[i][1], sun[i][1], 12, TEXT); }
                pad(R.id.sun, in, 8, 0, 0);
            }
        }
        moon(D, m.moonNow);
        pad(R.id.col_r, 12 - in, 0, 0, 0);
        text(R.id.st, st, ST, INK);
        pad(R.id.r2, 0, 4, 0, 0);
        counter(CS, rem);
        text(R.id.dt, date, T, TEXT);
        text(R.id.tm, time, T, MUTED);
        pad(R.id.when, 12, 0, 0, CS * 0.14f);
        text(R.id.ml, ml, T, MUTED);
        pad(R.id.ml, 0, 4, 0, 0);
        show(R.id.dl, det);
        if (det) { text(R.id.dl, dl, T, TEXT2); pad(R.id.dl, 0, 2, 0, 0); }
        show(R.id.kala, kala);
        if (kala) { kala(KS); pad(R.id.kala, 0, 5, 0, 0); }
    }

    // ================================================================== Day & night

    /** The bar picture into bar_l / bar_d (system theme) or bar_x (a forced one). widthDp: the width it is shown at. */
    private void bar(WidgetModel.Day d, int cur, float widthDp) {
        float[] parts = WidgetPlan.barParts(d.partStart, d.partEnd);
        float now = WidgetPlan.nowMark(m.now, d.partStart[0], d.partEnd[5]);
        if (theme == SYSTEM) {
            Bitmap l = WidgetBar.render(ctx, widthDp, k, parts, cur, now, LIGHT_C[PART_DAY], LIGHT_C[PART_NIGHT], LIGHT_C[ACCENT], LIGHT_C[TEXT]);
            Bitmap dk = WidgetBar.render(ctx, widthDp, k, parts, cur, now, DARK_C[PART_DAY], DARK_C[PART_NIGHT], DARK_C[ACCENT], DARK_C[TEXT]);
            bitmapBytes += l.getByteCount() + dk.getByteCount();
            rv.setImageViewBitmap(R.id.bar_l, l);
            rv.setImageViewBitmap(R.id.bar_d, dk);
            show(R.id.bar_x, false); show(R.id.bar_l, true); show(R.id.bar_d, true);
        } else {
            int[] c = forced();
            Bitmap x = WidgetBar.render(ctx, widthDp, k, parts, cur, now, c[PART_DAY], c[PART_NIGHT], c[ACCENT], c[TEXT]);
            bitmapBytes += x.getByteCount();
            rv.setImageViewBitmap(R.id.bar_x, x);
            show(R.id.bar_x, true); show(R.id.bar_l, false); show(R.id.bar_d, false);
        }
    }

    private boolean dayNight() {
        if (m.partIdx < 0 || m.kala == WidgetModel.NONE) return false;   // the parts are not known right now (just before the first dawn): the placeholder
        WidgetModel.Day d = m.days.get(m.partDay);
        int cur = m.partIdx;
        String pn = tx.get("part." + d.partName[cur]);
        int dot = pn.indexOf(" · ");
        String name = dot > 0 ? pn.substring(0, dot) : pn, desc = dot > 0 ? pn.substring(dot + 3) : null;
        String until = tx.fmt("w.until", "time", d.partTo[cur]), left = kalaLeft();
        if (w < 200) {   // a cell two columns wide: the same widget, stacked
            final float NS = 18.5f, T = 12.5f, S = 11.5f, G = 4;
            String[] tk = { d.partFrom[0], d.sunset.hm, d.partTo[5] };
            float ticks = mw(RG, S, tk[0], true) + 8 + mw(RG, S, tk[1], true) + 8 + mw(RG, S, tk[2], true);
            float needH = 24 + lh(NS) + lh(T) + G + lh(T) + 1 + lh(S) + G + WidgetBar.HEIGHT + 1 + lh(S);
            fit(24 + max(mw(SB, NS, name), mw(RG, T, until), kalaW(T), mw(RG, S, left), ticks), needH, 0.6f, 2.2f);
            float g = WidgetPlan.gap(h, k, needH, 2, G, 12);
            start(R.layout.w2_day_s);
            pad(R.id.w_c, 12, 12, 12, 12);
            text(R.id.name, name, NS, TEXT);
            text(R.id.sub, until, T, MUTED);
            kala(T); pad(R.id.kala, 0, g, 0, 0);
            text(R.id.left, left, S, MUTED); pad(R.id.left, 0, 1, 0, 0);
            bar(d, cur, w - 24 * k); pad(R.id.bar, 0, g, 0, 0);
            for (int i = 0; i < 3; i++) text(new int[] { R.id.tk0, R.id.tk1, R.id.tk2 }[i], tk[i], S, MUTED);
            pad(R.id.tks, 0, 1, 0, 0);
            return true;
        }
        final float NS = 22, T = 12.5f, KS = 13.5f, S = 11.5f, LS = 13, ROW = 25;
        if (desc != null && tx.ru() && "majjhanhika".equals(d.partName[cur])) desc += " дня";
        String sub = (desc != null ? desc + " · " : "") + until;
        float needW = 32 + max(mw(SB, NS, name), mw(RG, T, sub)) + 16 + max(kalaW(KS), mw(RG, T, left));
        float head = lh(NS) + lh(T) + 12 + WidgetBar.HEIGHT + 1 + lh(S), listH = 8 + 6 * ROW + 8 + lh(12);
        boolean tall = h >= 24 + head + listH;   // a tall one adds the six parts with their borders and the sun
        fit(needW, 24 + head + (tall ? listH : 0), 0.6f, tall ? 1.5f : 2.2f);
        start(R.layout.w2_day_m);
        pad(R.id.w_c, 16, 12, 16, 12);
        text(R.id.name, name, NS, TEXT);
        text(R.id.sub, sub, T, MUTED);
        kala(KS);
        text(R.id.left, left, T, MUTED); pad(R.id.left, 0, 1, 0, 0);
        bar(d, cur, w - 32 * k); pad(R.id.bar, 0, 12, 0, 0);
        String[] tk = { d.partFrom[0], d.noon.hm, d.sunset.hm, d.partTo[5] };
        for (int i = 0; i < 4; i++) text(new int[] { R.id.tk0, R.id.tk1, R.id.tk2, R.id.tk3 }[i], tk[i], S, MUTED);
        pad(R.id.tks, 0, 1, 0, 0);
        show(R.id.list, tall); show(R.id.sun, tall);
        if (tall) {
            pad(R.id.list, 0, 8, 0, 0);
            rv.removeAllViews(R.id.list);
            for (int i = 0; i < 6; i++) {
                RemoteViews row = new RemoteViews(ctx.getPackageName(), i == cur ? R.layout.w2_part_row_cur : R.layout.w2_part_row);
                text(row, R.id.p_name, tx.get("part." + d.partName[i]), LS, TEXT);
                text(row, R.id.p_times, d.partFrom[i] + "–" + d.partTo[i], LS, TEXT);
                row.setViewPadding(R.id.p_row, px(8), 0, px(8), 0);
                if (i == cur) row.setInt(R.id.p_row, "setBackgroundResource", bg(PLATE));
                rv.addView(R.id.list, row);
            }
            String[][] sun = { { tx.get("sunrise"), d.sunrise.hm }, { tx.get("noon"), d.noon.hm }, { tx.get("sunset"), d.sunset.hm } };
            int[][] ids = { { R.id.s0l, R.id.s0t }, { R.id.s1l, R.id.s1t }, { R.id.s2l, R.id.s2t } };
            for (int i = 0; i < 3; i++) { text(ids[i][0], sun[i][0] + " ", 12, TEXT2); text(ids[i][1], sun[i][1], 12, TEXT); }
            pad(R.id.sun, 0, 8, 0, 0);
        }
        return true;
    }

    // ================================================================== Calendar 4x4

    private void calendar() {
        // the month shown: today's, or one of the next two (the arrows; the data reaches about eleven weeks ahead)
        int y0 = WidgetFormat.year(m.today), m0 = WidgetFormat.month(m.today) - 1 + Math.max(0, Math.min(WidgetProvider.MONTHS_AHEAD, monthOff));
        int[] mo = WidgetModel.month(WidgetModel.ymd(y0 + m0 / 12, m0 % 12 + 1, 1), m.weekStart);   // year, month, offset, days, rows
        int weeks = mo[4];
        final float BASE_W = 290, T = 12.5f;
        k = WidgetPlan.scale(w, h, BASE_W, WidgetPlan.calMinH(weeks), 0.7f, 1.4f);
        boolean det = det(), allMoons = WidgetConfig.pick(cfg.moons, m.allMoons);
        int[] plan = WidgetPlan.cal(h / k, weeks, det, cfg.next);   // next rows, card, the card's detail line, moons
        start(R.layout.w2_cal);
        pad(R.id.w_c, 14, 14, 14, 14);
        text(R.id.month, tx.monthName(mo[1]) + " " + mo[0], 17, TEXT);
        pad(R.id.hd, 2, 0, 0, 5);
        int off = Math.max(0, Math.min(WidgetProvider.MONTHS_AHEAD, monthOff));
        tintImage(R.id.nav_prev, TEXT2); tintImage(R.id.nav_next, TEXT2);
        rv.setInt(R.id.nav_prev, "setImageAlpha", off > 0 ? 255 : 70);
        rv.setInt(R.id.nav_next, "setImageAlpha", off < WidgetProvider.MONTHS_AHEAD ? 255 : 70);
        rv.setViewPadding(R.id.nav_prev, px(10), 0, px(6), 0);
        rv.setViewPadding(R.id.nav_next, px(6), 0, 0, 0);
        rv.setOnClickPendingIntent(R.id.nav_prev, WidgetProvider.nav(ctx, widgetId, -1, drawnH));
        rv.setOnClickPendingIntent(R.id.nav_next, WidgetProvider.nav(ctx, widgetId, 1, drawnH));
        for (int i = 0; i < 7; i++) {
            String s = tx.weekday(m.weekStart == 0 ? (i + 6) % 7 : i);
            text(WD[i], tx.ru() ? s : s.substring(0, 2), 10.5f, MUTED);
        }
        pad(R.id.wk, 0, 0, 0, 3);
        // the grid: whole weeks, the neighbouring months' days in grey
        rv.removeAllViews(R.id.grid);
        long first = WidgetFormat.daysFromCivil(mo[0], mo[1], 1) - mo[2];
        for (int r = 0; r < weeks; r++) rv.addView(R.id.grid, week(first + r * 7L, mo[1], r, plan[3] == 1, allMoons));
        // the card of today
        boolean card = plan[1] == 1;
        show(R.id.card, card);
        if (card) {
            pad(R.id.grid, 0, 0, 0, 8);
            rv.setInt(R.id.card, "setBackgroundResource", bg(CARD));
            pad(R.id.card, 12, 9, 12, 9);
            WidgetModel.Upo u = m.cur();
            int dow = WidgetFormat.dow(WidgetFormat.year(m.today), WidgetFormat.month(m.today), WidgetFormat.day(m.today));
            text(R.id.cdate, tx.item("w.weekdaysLong", dow) + ", " + WidgetFormat.day(m.today) + " " + tx.item("w.monthsOf", WidgetFormat.month(m.today) - 1), 13.5f, TEXT);
            show(R.id.badge, m.ongoing);
            if (m.ongoing) {
                text(R.id.badge, tx.get("w.upoDay"), 10.5f, INK);
                rv.setInt(R.id.badge, "setBackgroundResource", bg(BADGE));
                pad(R.id.badge, 8, 1.5f, 8, 1.5f);
            }
            String st = status(u), full, brief;
            if (m.ongoing) { full = " · " + tx.fmt("w.until", "time", dateLabel(u.end.ymd) + ", " + u.end.hm); brief = " · " + tx.fmt("w.until", "time", u.end.hm); }
            else { full = " · " + dateLabel(u.start.ymd) + ", " + tx.fmt("w.from", "time", u.start.hm); brief = " · " + dateLabel(u.start.ymd); }
            float room = BASE_W - 28 - 24 - 2 - mw(BD, T, st);
            text(R.id.c_st, st, T, INK);
            text(R.id.c_until, mw(RG, T, full) <= room ? full : brief, T, MUTED);
            pad(R.id.cl2, 0, 1, 0, 0);
            text(R.id.cl3, moonLine() + (plan[2] == 1 ? " · " + tx.fmt("w.lunarDay", "n", WidgetPlan.tithi(m.moonNow)) : ""), T, TEXT2);
            WidgetModel.Day d = m.dayIdx >= 0 ? m.days.get(m.dayIdx) : null;
            boolean sun = plan[2] == 1 && d != null;
            show(R.id.cl4, sun);
            if (sun) {   // the sun of today; when the three do not fit in the line, the noon goes (the kala line has it)
                String rise = tx.get("sunrise") + " " + d.sunrise.hm, set = tx.get("sunset") + " " + d.sunset.hm, all = rise + " · " + tx.get("noon") + " " + d.noon.hm + " · " + set;
                text(R.id.cl4, mw(RG, T, all) <= BASE_W - 28 - 24 - 2 ? all : rise + " · " + set, T, MUTED);
            }
        }
        // the next Uposathas: as many rows as the height has left
        boolean list = nextRows(plan[0], 0);
        show(R.id.nx, list);
        if (list) pad(R.id.nx, 0, 8, 0, 0);
    }

    /** The list "Next" (ids nlab, nlist): up to n Uposathas after the current one: moon, the date it begins on, the day, "in N d"; extraPad: more room above and below each row (base dp). False: nothing to list. */
    private boolean nextRows(int n, float extraPad) {
        List<WidgetModel.Upo> next = m.following(Math.max(0, n));
        rv.removeAllViews(R.id.nlist);
        if (next.isEmpty()) return false;
        text(R.id.nlab, tx.get("next"), 10.5f, MUTED);
        float dateW = 0;
        for (WidgetModel.Upo u : next) dateW = Math.max(dateW, mw(SB, 13, dateLabel(u.start.ymd)));
        for (WidgetModel.Upo u : next) {
            RemoteViews row = new RemoteViews(ctx.getPackageName(), R.layout.w2_next_row);
            row.setImageViewBitmap(R.id.r_moon, mini(18, u.nominal()));
            text(row, R.id.r_date, dateLabel(u.start.ymd), 13, TEXT);   // the date it BEGINS on (the evening), as the app's own lists say
            row.setInt(R.id.r_date, "setWidth", px(8 + dateW * 1.03f + 12));
            row.setViewPadding(R.id.r_date, px(8), 0, 0, 0);
            text(row, R.id.r_day, dayN(u), 13, TEXT2);
            text(row, R.id.r_in, inText(u), 13, MUTED);
            row.setViewPadding(R.id.n_row, 0, px(3.5f + extraPad), 0, px(3.5f + extraPad));
            rv.addView(R.id.nlist, row);
        }
        return true;
    }

    /** One week of the grid from the day count `start`: seven tiles, each a tap target that opens the calendar on that day. */
    /** A date of an Uposatha: the evening it begins on or its own day. */
    private boolean marked(long day) {
        String ymd = WidgetFormat.ymdFromDays(day);
        return m.startingOn(ymd) != null || m.uposathaOn(ymd) != null;
    }

    private RemoteViews week(long start, int month, int r, boolean moons, boolean allMoons) {
        RemoteViews row = new RemoteViews(ctx.getPackageName(), R.layout.w2_cal_week);
        for (int c = 0; c < 7; c++) {
            String ymd = WidgetFormat.ymdFromDays(start + c);
            int day = WidgetFormat.day(ymd);
            boolean in = WidgetFormat.month(ymd) == month, today = ymd.equals(m.today), past = ymd.compareTo(m.today) < 0;
            WidgetModel.Upo startOf = m.startingOn(ymd), dayOf = m.uposathaOn(ymd);
            // Every date of an Uposatha carries the same solid mark - the evening it begins on and its own day (by the suttas two dates) -
            // and neighbouring dates are joined into one capsule: the band runs from the middle of a date to the middle of the next,
            // through the edge of the cell; at the end of a row it stops at the edge and goes on from the edge of the next row. They used
            // to differ (a filled circle for the evening, a dim tile for the day), and on the day itself the widget looked "as if today
            // were no Uposatha" (owner, 2026-10-11: "all of these are Uposathas, it must be the same, and clear").
            boolean solid = in && marked(start + c);
            boolean band = false;
            row.setViewPadding(CG[c], px(1.5f), px(1.5f), px(1.5f), px(1.5f));
            row.setViewVisibility(CG[c], in ? View.VISIBLE : View.INVISIBLE);
            if (in) row.setImageViewResource(CG[c], today ? bg(TILE_TODAY) : bg(TILE));
            row.setViewVisibility(CO[c], today && in ? View.VISIBLE : View.GONE);   // the frame of today again, on top: the band of an Uposatha would cover the tile's own
            if (today && in) { row.setImageViewResource(CO[c], bg(RING)); row.setViewPadding(CO[c], px(1.5f), px(1.5f), px(1.5f), px(1.5f)); }
            row.setInt(HL[c], "setHeight", px(22));
            row.setInt(HR[c], "setHeight", px(22));
            row.setInt(HL[c], "setBackgroundResource", solid && marked(start + c - 1) ? R.drawable.w2_band : 0);
            row.setInt(HR[c], "setBackgroundResource", solid && marked(start + c + 1) ? R.drawable.w2_band : 0);
            boolean bold = solid || band || (today && in);
            int shown = bold ? CB[c] : CT[c];
            row.setViewVisibility(CT[c], bold ? View.GONE : View.VISIBLE);
            row.setViewVisibility(CB[c], bold ? View.VISIBLE : View.GONE);
            text(row, shown, String.valueOf(day), 13.5f, solid ? ON_ACCENT : band ? INK : !in || (past && !today) ? MUTED : TEXT);
            if (solid) {   // the number in a filled circle
                row.setInt(shown, "setBackgroundResource", R.drawable.w2_dot);
                row.setInt(shown, "setWidth", px(22));
                row.setInt(shown, "setHeight", px(22));
            }
            boolean moon = moons && in && (solid || band || allMoons);
            row.setViewVisibility(CM[c], moon ? View.VISIBLE : View.GONE);
            if (moon) {
                double f = solid ? (startOf != null ? startOf : dayOf).nominal() : band ? dayOf.nominal() : m.phaseOn(ymd);
                row.setImageViewBitmap(CM[c], mini(allMoons ? 12 : 11, f));
                row.setViewPadding(CM[c], 0, px(1), 0, 0);
            }
            row.setOnClickPendingIntent(CELL[c], WidgetProvider.openApp(ctx, widgetId, 3 + r * 7 + c, WidgetProvider.route(WidgetPlan.CAL, ymd)));
        }
        return row;
    }

    // ================================================================== no data yet

    private void placeholder(JSONObject data) {
        String lang = null;
        if (data != null) {
            JSONObject st = data.optJSONObject("settings");
            lang = st != null ? st.optString("lang", "en") : "en";
        }
        if (lang == null) lang = Locale.getDefault().getLanguage();
        tx = new WidgetText(ctx, lang);
        String title = tx.get("w.open"), body = tx.get(data != null ? "w.stale" : "w.noData");
        boolean small = kind == WidgetPlan.MOON || h < 90 || w < 100;
        final float D = small ? 30 : 44;
        fit(16 + max(box(D), mw(SB, 12.5f, title), small ? 0 : mw(RG, 11, body)), 16 + box(D) + 2 + lh(12.5f) + (small ? 0 : 1 + lh(11)), 0.5f, 2.2f);
        start(R.layout.w2_ph);
        moon(D, 0.5);
        text(R.id.title, title, small ? 11 : 12.5f, TEXT);
        pad(R.id.title, 0, 2, 0, 0);
        show(R.id.body, !small);
        if (!small) { text(R.id.body, body, 11, MUTED); pad(R.id.body, 0, 1, 0, 0); }
        frame(WidgetProvider.route(slide >= 0 ? kind : WidgetPlan.UPO, null));
    }
}
